- name: Check KVM and deploy VMs
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - step1_check_kvm.yaml
    - step2_check_networks.yaml
    - step3_check_resources.yaml
    - step4_create_vms.yaml
    - step5_final_check.yaml

  