# The cloud image is a thin vm. only has 2G of diskspace even though we give it +10G

- name: install package to resize diskspace of this VM
  become: true
  apt:
    name: cloud-initramfs-growroot
    state: present
  ignore_errors: true

- name: reboot VM
  become: true
  ansible.builtin.reboot:

- name: resize filesystem
  become: true
  ansible.builtin.shell: resize2fs /dev/vda1

- name: Check system freespace
  ansible.builtin.shell: df /dev/vda1 --output\=avail | tail -1
  register: freespace
    
- fail:
    msg: system does not have the minimum space required to continue (5Gb requested). 
  when: freespace.stdout|float is lt 5000000


# apt install cloud-initramfs-growroot
# reboot

# root@probeprimary:~# lsblk
# NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
# loop0     7:0    0  63.4M  1 loop /snap/core20/1974
# loop1     7:1    0 111.9M  1 loop /snap/lxd/24322
# loop2     7:2    0  53.3M  1 loop /snap/snapd/19457
# vda     252:0    0  12.2G  0 disk
# ├─vda1  252:1    0  12.1G  0 part /
# ├─vda14 252:14   0     4M  0 part
# └─vda15 252:15   0   106M  0 part /boot/efi

# root@probeprimary:~# df -hT | grep /dev/vda
# /dev/vda1      ext4   2.0G  1.9G   89M  96% /           << ONLY 2G
# /dev/vda15     vfat   105M  6.1M   99M   6% /boot/efi

# root@probeprimary:~# resize2fs /dev/vda1
# resize2fs 1.46.5 (30-Dec-2021)
# Filesystem at /dev/vda1 is mounted on /; on-line resizing required
# old_desc_blocks = 1, new_desc_blocks = 2
# The filesystem on /dev/vda1 is now 3169531 (4k) blocks long.

# root@probeprimary:~# df -h
# Filesystem      Size  Used Avail Use% Mounted on
# tmpfs           197M  1.1M  196M   1% /run
# /dev/vda1        12G  1.9G  9.8G  16% /                 << NOW 12G
# tmpfs           982M     0  982M   0% /dev/shm
# tmpfs           5.0M     0  5.0M   0% /run/lock
# /dev/vda15      105M  6.1M   99M   6% /boot/efi
# tmpfs           197M  4.0K  197M   1% /run/user/0