apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-data-pvc
  labels:
    type: "nfs"
    application: "backend"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: csv-data-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    type: "nfs"
    application: "influxdb"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: influxdb-shared
---
