- name: Ping test
  ansible.builtin.ping:

- name: Add ssh key for ansible
  ansible.posix.authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB9lxRAMb/ta9bQQA/3NhlaKXsYrW5flo5s6HL0xBS2G ansible"


- name: Perform a dist-upgrade
  tags: always
  ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
      force_apt_get: true
  when: ansible_distribution == "Ubuntu"

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
      autoremove: yes