apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-nfs-server"
spec:
  type: {{ index .Values "nfs-server" "service" "type" }}
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      protocol: TCP
  selector:
    app: nfs-server

---
