apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Release.Name }}-nfs-client"
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  server: localhost
  path: /exports
  mountOptions: vers=4.2