{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample.fullname" . }}-influxdb-secret
  labels:
    {{- include "sample.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb-secret
    environment: {{ .Values.global.environment | default "dev" }}
type: Opaque
data:
  influxdb-token: {{ .Values.influxdb.token | b64enc | quote }}
  influxdb-password: {{ .Values.influxdb.auth.adminPassword | b64enc | quote }}
  influxdb-username: {{ .Values.influxdb.auth.adminUser | b64enc | quote }}
  influxdb-org: {{ .Values.influxdb.org | b64enc | quote }}
  influxdb-bucket: {{ .Values.influxdb.bucket | b64enc | quote }}
{{- end }}
